export const projectRoot = process.cwd();

export const TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmYxMWVkZGM4ODBkZjUwODNjMzAyY2QiLCJzdGVhbSI6eyJzdGVhbUlENjQiOiI3NjU2MTE5OTAwNzI3MzUyMyJ9LCJpYXQiOjE3MzkyNzkxODMsImV4cCI6MTczOTM2NTU4M30.2rAYdXD2mN5WDghfAIf62-e0LtzkoJu0GNFLKCr3HYI".trim()

export const TAXA = 0.06