export const projectRoot = process.cwd();

export const TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmYxMWVkZGM4ODBkZjUwODNjMzAyY2QiLCJzdGVhbSI6eyJzdGVhbUlENjQiOiI3NjU2MTE5OTAwNzI3MzUyMyJ9LCJpYXQiOjE3Mzc5ODE4MjMsImV4cCI6MTczODA2ODIyM30.GzVNLmDg88smr3tgzcgO-FZZY3fc2dOoQr5ZSdrb0Qk".trim()

export const TAXA = 0.07